### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'dlink_presence'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'dlink_presence'

### ISSUE THREAD

**Issue by NeroWard** [ayavilevich/homeassistant-dlink-presence#3]
No 'version' key in the manifest file for custom integration 'dlink_presence'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'dlink_presence'. Home Assistant 2021.3.4

**Comment by ayavilevich** [comment]
https://github.com/ayavilevich/homeassistant-dlink-presence/commit/f5e4d1f32200fe29fee4aecc64daf20e63d8b1ac

Please update to latest version and close the issue if resolved.

**Comment by NeroWard** [comment]
Works. The error is gone. Thanks!
